## Questionário 42 (Q42)

Orientações: 

- Registre suas respostas no questionário de mesmo nome no SIGAA.
- O tempo de registro das respostas no questionário será de 10 minutos. Portanto, resolva primeiro as questões e depois registre-as.
- Haverá apenas 1 (uma) tentativa de resposta.
- Submeta seu arquivo-fonte (utilizado para resolver as questões) em formato _.ipynb_ pelo SIGAA anexando-o à Tarefa denominada "Envio de arquivo" correspondente ao questionário.

*Nota:* o arquivo-fonte será utilizado apenas como prova de execução da tarefa. Nenhuma avaliação será feita quanto ao estilo de programação.

<hr>

**Questão 1.** No _dataset_ [enem2019.xlsx](https://github.com/gcpeixoto/ICD/blob/main/database/enem2019.xlsx), estão disponíveis as notas médias por estado obtidas nas provas do ENEM 2019. Supondo que _x_ é a diferença entre a amplitude da quantidade de inscritos na região Sudeste e a amplitude da quantidade de inscritos na região Norte, e que _y_ é o desvio médio para a série da quantidade total de inscritos de ensino médio público apenas para os estados do sul, assinale a alternativa que corretamente expressa os valores de _x_ e _y_,  nesta sequência.

**Obs.:** considere apenas a parte inteira do desvio médio.

***A. 149465 e 5690***

B. 169265 e 6593

C. 149465 e 0

D. 173921 e 2


<div class="alert alert-block alert-success">
    <b>Resposta:</b> A. 149465 e 5690
</div>

In [2]:
# O primeiro dígito da coluna "COD UF" corresponde à região que aquele estado pertence, de tal maneira:
# 1 = Norte
# 2 = Noreste
# 3 = Sudeste
# 4 = Sul
# 5 = Centro-Oeste


import pandas as pd

df = pd.read_excel(
    "https://raw.githubusercontent.com/gcpeixoto/ICD/main/database/enem2019.xlsx"
)
df["COD UF"] = df["COD UF"].astype(str)


# Separando o dataframe original em dois:
df_norte = pd.DataFrame(columns=df.keys())
df_sudeste = pd.DataFrame(columns=df.keys())
df_sul = pd.DataFrame(columns=df.keys())
for i in range(len(df)):
    if df.at[i, "COD UF"].startswith("1"):
        df_norte = df_norte.append(df.iloc[i])
    elif df.at[i, "COD UF"].startswith("3"):
        df_sudeste = df_sudeste.append(df.iloc[i])
    elif df.at[i, "COD UF"].startswith("4"):
        df_sul = df_sul.append(df.iloc[i])
# Definindo as amplitudes
norte_amp   = df_norte['Quantidade de Inscritos'].max() - df_norte['Quantidade de Inscritos'].min()
sudeste_amp = df_sudeste['Quantidade de Inscritos'].max() - df_sudeste['Quantidade de Inscritos'].min()

# Garantindo que os elementos da série df_sul['Total de inscritos de Ensino Médio Público'] são números:
df_sul['Total de inscritos de Ensino Médio Público'] = df_sul['Total de inscritos de Ensino Médio Público'].astype(float)


# Respostas
x = sudeste_amp - norte_amp
y = df_sul['Total de inscritos de Ensino Médio Público'].mad()

In [90]:
print(f"A diferença X entre a amplitude de inscritos nos estados do sudeste e a amplitude de inscritos nos estados do norte é de: {x}")
print(f"O desvio médio Y para a série da quantidade total de inscritos de ensino médio público apenas para os estados do sul é de: {y}")

A diferença X entre a amplitude de inscritos nos estados do sudeste e a amplitude de inscritos nos estados do norte é de: 149465
O desvio médio Y para a série da quantidade total de inscritos de ensino médio público apenas para os estados do sul é de: 5690.666666666667

**Questão 2.** Calcule o percentual _p_ de inscritos para o ENEM 2019 provenientes do ensino privado de todos os Estados em relação ao total de inscritos no exame, bem como o valor do quociente _v/V_, onde _v_ é a variância para a série do total de inscritos provenientes do ensino público e _V_ a variância para a série do total de inscritos provenientes do ensino privado. Assinale a alternativa correta para _p_ e _v/V_.

***A. 11.4% e 34.48***

B. 15% e 33.45

C. 12.5% e 36.78

D. 13.54% e 34.6

<div class="alert alert-block alert-success">
    <b>Resposta:</b> A. 11.4% e 34.48
</div>

In [99]:
df = pd.read_excel(
    "https://raw.githubusercontent.com/gcpeixoto/ICD/main/database/enem2019.xlsx"
)

# Garantindo que são números e não objects
df['Total de inscritos de Ensino Médio Privado'] = df['Total de inscritos de Ensino Médio Privado'].astype(int)
df['Quantidade de Inscritos'] = df['Quantidade de Inscritos'].astype(int)

# o percentual p de inscritos para o ENEM 2019 provenientes do ensino
# privado de todos os Estados em relação ao total de inscritos no exame
p = df['Total de inscritos de Ensino Médio Privado'].sum()/df['Quantidade de Inscritos'].sum() * 100


# valor do quociente v/V, onde v é a variância para a série do total de inscritos provenientes
# do ensino público e V a variância para a série do total de inscritos provenientes do ensino privado
v = df['Total de inscritos de Ensino Médio Público'].var()
V = df['Total de inscritos de Ensino Médio Privado'].var()

In [100]:
print(f"O valor para p é: {p}%")
print(f"A razão entre v e V é de: {v/V}")

O valor para p é: 11.4655415840169%
A razão entre v e V é de: 34.47957929225895

**Questão 3.** Defina a nota média $N(x)$ de cada região brasileira $x$ como a média das notas $N_i$ de cada uma das $Q$ grandes áreas de conhecimento que constam da prova do ENEM 2019, isto é,

$$N(x) =  \frac{ \sum_{i=1}^Q N_i(x)}{Q},$$

e assinale a alternativa cujas regiões detém o primeiro e o segundo maiores valores de desvio padrão.

A. Nordeste e Sudeste

B. Sudeste e Nordeste

C. Norte e Sul

D. Sul e Centro-Oeste

In [3]:
df = pd.read_excel(
    "https://raw.githubusercontent.com/gcpeixoto/ICD/main/database/enem2019.xlsx"
)
df["COD UF"] = df["COD UF"].astype(str)
# 1 = Norte
# 2 = Noreste
# 3 = Sudeste
# 4 = Sul
# 5 = Centro-Oeste

In [ ]:
# Defina a nota média  N(x)  de cada região brasileira  x  como a média das
# notas  Ni  de cada uma das  Q  grandes áreas de conhecimento
# que constam da prova do ENEM 2019, isto é,

In [11]:
def definir_regiao(row):
    if row["COD UF"].startswith("1"):
        return "Norte"
    elif row["COD UF"].startswith("2"):
        return "Nordeste"
    elif row["COD UF"].startswith("3"):
        return "Sudeste"
    elif row["COD UF"].startswith("4"):
        return "Sul"
    else:
        return "Centro-Oeste"


# Criando a coluna médias
medias = []
for i in range(len(df)):
    soma = 0
    for key in df.keys():
        if "Média" in key:
            soma += df.at[i, key]
    medias.append(soma / 5)
df['Nota Média'] = medias
# Criando coluna Região
df["Região"] = df.apply(lambda row: definir_regiao(row), axis=1)

In [29]:
df

,COD UF,Estado,Quantidade de Inscritos,Total de inscritos de Ensino Médio Público,Total de inscritos de Ensino Médio Privado,Média da nota da prova de Ciências da Natureza,Média da nota da prova de Ciências Humanas,Média da nota da prova de Linguagens e Códigos,Média da nota da prova de Matemática,Média da nota da prova de redação,Nota Média,Região
0,43,RS,46173,41424,4749,484.659842,524.267227,533.906006,546.707112,598.457500,537.599537,Sul
1,16,AP,6136,5711,425,446.884217,477.089716,491.826222,477.948733,538.818381,486.513453,Norte
2,27,AL,17551,15328,2223,453.600683,480.601937,496.041317,498.075512,553.236927,496.311275,Nordeste
3,13,AM,25817,24541,1276,446.577429,475.833558,494.953598,482.391837,509.776809,481.906646,Norte
4,52,GO,35546,31323,4223,477.625078,505.805269,520.101327,528.496087,594.747233,525.354999,Centro-Oeste
5,53,DF,21075,16488,4587,491.416323,521.916533,537.273155,540.552689,606.064022,539.444545,Centro-Oeste
6,15,PA,46742,42100,4642,454.386761,481.895274,493.224433,486.183729,562.508171,495.639673,Norte
7,26,PE,61506,55191,6315,464.062071,491.227411,506.697136,515.049252,558.769121,507.160998,Nordeste
8,22,PI,24156,21457,2699,458.422668,482.635566,497.002756,501.978563,577.567990,503.521509,Nordeste
9,28,SE,13494,11261,2233,464.918482,491.793049,505.815090,508.695031,604.263188,515.096968,Nordeste
10,42,SC,34646,30937,3709,488.451978,522.626599,531.496343,548.319166,587.808690,535.740555,Sul
11,17,TO,9087,8627,460,455.306262,478.853000,497.216411,496.567979,558.849777,497.358686,Norte
12,51,MT,18022,16515,1507,465.892259,493.876876,506.193957,508.679835,559.808250,506.890236,Centro-Oeste
13,25,PB,26938,23442,3496,463.969121,491.600768,504.116981,509.135298,585.282333,510.820900,Nordeste
14,21,MA,43497,41377,2120,443.420893,469.198684,487.217335,480.233747,527.142178,481.442567,Nordeste
15,24,RN,20349,17686,2663,475.937653,502.031469,516.174350,523.480033,598.369859,523.198673,Nordeste
16,41,PR,52788,46058,6730,487.354390,519.390627,529.712041,541.746659,570.283666,529.697477,Sul
17,12,AC,5330,5054,276,454.615066,482.340857,500.330089,491.772480,558.310209,497.473740,Norte
18,33,RJ,73086,58065,15021,489.631863,519.930533,533.396993,541.914833,605.732021,538.121249,Sudeste
19,23,CE,112313,106275,6038,451.870939,477.932753,492.956706,498.939480,526.061777,489.552331,Nordeste
20,14,RR,2203,2030,173,464.764538,493.750264,506.722809,504.817560,521.731785,498.357391,Norte
21,11,RO,12069,11681,388,458.499847,485.541271,502.057741,501.310154,548.389847,499.159772,Norte
22,32,ES,25422,23187,2235,484.889184,512.252211,521.987041,543.111366,601.254706,532.698902,Sudeste
23,31,MG,108173,97493,10680,488.408591,516.265989,527.469714,547.928061,605.138213,537.042114,Sudeste
24,35,SP,219426,185540,33886,488.628185,521.312772,535.519439,547.016915,582.410304,534.977523,Sudeste
25,50,MS,15539,14237,1302,473.982698,501.326601,517.284766,519.630141,571.824870,516.809815,Centro-Oeste
26,29,BA,70328,62827,7501,462.197014,490.913791,505.594393,502.835294,561.313678,504.570834,Nordeste

In [17]:
df['Nota Média']

18.962094856362125

In [196]:
media = 0
for i in range(len(df)):
    if df.at[i,'Região'] == "Sul":
        media += df.at[i,"Média da nota da prova de Matemática"]
       # media += df.at[i, 'Média da nota da prova de Ciências da Natureza']
       # media += df.at[i, 'Média da nota da prova de Ciências Humanas']
       # media += df.at[i, 'Média da nota da prova de Linguagens e Códigos']
       # media += df.at[i, 'Média da nota da prova de redação']

In [195]:
media/15

534.3458565294196

In [199]:
media/3

545.590979239991

In [136]:
df['Nota Média'].std()

18.962094856362125